### ISSUE TITLE
Help needed: Implementing "Sign in with Google" in .NET MAUI 

### ISSUE THREAD

**Issue by NazrinAli12** [AdamEssenmacher/MemoryToolkit.Maui#29]
Hi AdamEssenmacher,

I am currently learning .NET MAUI and trying to implement the "Sign in with Google" feature. However, I am facing some difficulties, as I need to do this without using Microsoft Azure, as per my teacher's recommendation.

Could you please guide me on how to implement this feature or share any resources or sample code that could help? I would greatly appreciate your support!

Thank you in advance for your time and help.

Best regards,
Nazrin

**Comment by AdamEssenmacher** [comment]
Hi @NazrinAli12,

This Issues section is specifically for reporting bugs or requesting features related to MemoryToolkit.Maui. It's not the right place to ask general questions unrelated to this project like "Sign In with Google" in a MAUI app.

I recommend trying some of these platforms where you'll find a broader community ready to help:

- [dotnet/maui Discussions](https://github.com/dotnet/maui/discussions)
- The .NET Discord Server
- [r/dotnetmaui on Reddit](https://reddit.com/r/dotnetmaui)

As a student, you might also consider reaching out to your instructor or leveraging resources provided by your school, like office hours or programming support. These can be excellent starting points for learning how to tackle such challenges!

Best of luck with your project!

**Comment by NazrinAli12** [comment]
Thank you for your answer, i will delete my questions.
