### ISSUE TITLE
Utilities class missing

### ISSUE THREAD

**Issue by Captnwalker1** [AdamEssenmacher/MemoryToolkit.Maui#3]
Was wanting to check this out and upon trying to build seems the Utilities class is missing?
E.x.
`var hostPage = Utilities.GetFirstSelfOrParentOfType<Page>(visualElement);`

https://github.com/AdamEssenmacher/MemoryToolkit.Maui/blob/a0640d72fe1f091b4dd0edb2168efaa645ed64a6/src/MemoryToolkit.Maui/GCMonitorBehavior.cs#L77

**Comment by AdamEssenmacher** [comment]
Doh!

I just split that out last night. It should be there now, thanks!
