### ISSUE TITLE
Suggestion: Disconnect bindingcontext before disconnecting controls

### ISSUE THREAD

**Issue by 420tech** [AdamEssenmacher/MemoryToolkit.Maui#6]
First, awesome job! We discovered your package after we discovered a memory leak. And as it happens, the leak itself was related to pushing/popping pages off the stack - the page wasn't be disposed properly. We are targeting Windows only (ATM) but likely to have Android release in future.

The suggestion I have is: clear the binding context before you disconnect the layouts. The reason is that if you use two-way binding, the backing viewmodel reset it's properties back to default (and that wasn't the behavior we were looking for). The proposed fix would be to modify AutoDisconnectBehavior.cs and move line 164 to line 151. 

Thanks again!

**Comment by AdamEssenmacher** [comment]
Thanks for the feedback. You're the first I've heard of anyone using it on Windows, so it's great to hear it was helpful on that platform.

I'm curious: was the leak you found an issue with MAUI, or just something in your code?

The two-way binding issue makes sense. Peeking back at the code, it could be more logically consistent. Breaking the views apart (i.e., nulling out Parent/Content properties, clearing children) should be its own discrete step of the process, regardless of when the BindingContext is cleared. Right now, it's happening in the middle.

So, ideally, it would look like:

1. Clear BindingContext
2. Clear references to other views
3. Disconnect handler (this one for sure needs to happen last)

I can make this change next time I have my hands in there, but I'd happily accept a PR in the meantime 😊

**Comment by 420tech** [comment]
Hi Adam, the leak appears to be Maui code - the page handlers are never disconnecting leaving the page still in memory. 

The project I am working on is Windows first - and Android sometime down the road. It is a tablet app (by design - client uses Windows tablets in their production environment) but are considering using Android tablets as well.

The page handlers not getting released was discovered using JetBrains dotMemory product - it clearly showed that page handlers were never released. Although the app itself only has a modest amount of pages (but a lot of custom views/controls), we were leaking very bad. 

I will give it a try to create a PR - probably over the weekend.

Thanks again for your work!

**Comment by 420tech** [comment]
I have a small PR ready - but can't push the branch. I get a 403 error (not authorized).

**Comment by AdamEssenmacher** [comment]
@420tech are you trying to push directly to this repo?

To contribute, you should create your own fork, push your changes there, and then initiate a PR from your updated fork.

**Comment by AdamEssenmacher** [comment]
Completed as part of my cleanup before releasing generally. Thanks again @420tech !
