### ISSUE TITLE
[Feature] Nuget Package

### ISSUE THREAD

**Issue by bcaceiro** [AdamEssenmacher/MemoryToolkit.Maui#7]
Hi Adam! Great work on this repo, are you planning to release a Nuget Package for an easier setup and installation soon?

Best regards

**Comment by AdamEssenmacher** [comment]
Yes this is on my todo list. There are some things I want to clean up (mostly around naming) before 'publishing' it officially.

I also wanted to get some feedback from the community and see how much of a demand there was for it. I think that mission has been accomplished now :)

**Comment by AdamEssenmacher** [comment]
Done! https://www.nuget.org/packages/AdamE.MemoryToolkit.Maui

**Comment by bcaceiro** [comment]
Thank you very much! Will give feedback if some issue occurs!
