### ISSUE TITLE
Setup Init Code via C# code, not XAML

### ISSUE THREAD

**Issue by appsure** [AdamEssenmacher/MemoryToolkit.Maui#9]
Hi Adam, thanks for building this!  I'm having trouble writing the equivilent C# for the XAML you provided to wire up a ContentPage.  Could you point me in the right direction?

**Comment by AdamEssenmacher** [comment]
You would just want to set or unset the attached behavior(s) in code I think:
```c#
    LeakMonitorBehavior.SetCascade(contentPage, true);
    TearDownBehavior.SetCascade(contentPage, true);
```

**Comment by AdamEssenmacher** [comment]
Closing the issue. Please feel free to open a discussion if you still need help here.

**Comment by appsure** [comment]
Thanks, it worked.  Testing it out now.

**Comment by RuddyOne** [comment]
@AdamEssenmacher As silly as it sounds I think you should put this on the front page. Took me a second to realise how to do it this way also. 

Great work so far on this project, I think its needed for most developers coming from XF. I am running into a ton of issues with MAUi also, leaks everywhere.
